<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ngohungphuc (Tony Hudson)  G</name>
   <tag></tag>
   <elementGuidId>e4037bb0-9d9a-48dd-90e0-a72f12b37251</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rso&quot;)/div[@class=&quot;_NId&quot;]/div[@class=&quot;srg&quot;]/div[@class=&quot;g&quot;]/div[@class=&quot;rc&quot;]/h3[@class=&quot;r&quot;]/a[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>return rwt(this,'','','','1','AFQjCNEAzvUPszr3Tsr7HNRLv4QBWHBMNw','','0ahUKEwjJ6Z7bk_fSAhVGerwKHfj7AJQQFggfMAA','','',event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=1&amp;ved=0ahUKEwjJ6Z7bk_fSAhVGerwKHfj7AJQQFggfMAA&amp;url=https%3A%2F%2Fgithub.com%2Fngohungphuc&amp;usg=AFQjCNEAzvUPszr3Tsr7HNRLv4QBWHBMNw&amp;bvm=bv.150729734,d.dGc</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ngohungphuc (Tony Hudson) · GitHub</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-href</name>
      <type>Main</type>
      <value>https://github.com/ngohungphuc</value>
   </webElementProperties>
</WebElementEntity>
